# Generated by Django 3.2.20 on 2023-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20231019_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='icons/'),
        ),
    ]
