# Generated by Django 3.2.20 on 2023-10-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
