# Generated by Django 3.2.20 on 2023-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
